// Poster data with categories
    const posters = [
        { id: 1, title: " Kendrick Lamar's DAMN. album cover", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/damnn.jpeg", category: "Music" },
        { id: 2, title: "DAMN. X SOS album cover", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/szaxken.jpeg", category: "Music" },
        { id: 3, title: "SZA's SOS album cover ", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/SOSSZA.jpeg", category: "Music" },
        { id: 4, title: "Muhammad Ali Motivation", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/aliiiinspiartion.png", category: "Sports" },
        { id: 5, title: "SZA SOS album cover", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/asos.png", category: "Inspirational Quotes" },
        { id: 6, title: "Chirping Birds", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/birdsnature.png", category: "Nature" },
        { id: 7, title: "BMW sports car", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/bmwcarrs.png", category: "Cars" },
        { id: 8, title: "Flower Boy album cover", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/creatormusic.png", category: "Music" },
        { id: 9, title: "Ducati Superleggera X BMW race car. ", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doubledugaticars.png", category: "Cars" },
        { id: 10, title: "Monaco Grand Prix X race car", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doubleformulasports.png", category: "Sports" },
        { id: 11, title: "Japanese philosophy of Kaizen", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doubleinspiration.png", category: "Inspirational Quotes" },
        { id: 12, title: "Michael Jordan X Kobe Bryant", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doublekobe.png", category: "Sports" },
        { id: 13, title: "Interstellar Movie poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doublemovie.png", category: "Movies" },
        { id: 14, title: "Messi X Maradona", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doublemrmessi.png", category: "Sports" },
        { id: 15, title: "Nature Photo", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doublenature.png", category: "Nature" },
        { id: 16, title: "Mindset Motivation", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/doublminsett.png", category: "Inspirational Quotes" },
        { id: 17, title: "Mindset Motivation", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/easyway.png", category: "Art" },
        { id: 18, title: "Eminem poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/eminem.png", category: "Music" },
        { id: 19, title: "Earth Rise poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/erthrisemovie.png", category: "Movies" },
        { id: 20, title: "Interstellar Movie Poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/intermovie.webp", category: "Movies" },
        { id: 21, title: "Kaizen Motivation", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/kaizen.png", category: "Inspirational Quotes" },
        { id: 22, title: "Acacia tree against a sunset sky", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/kenya.png", category: "Art" },
        { id: 23, title: "Kenyan Flag", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/kenyaa.png", category: "Inspirational Quotes" },
        { id: 24, title: "Qualityframes", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/qualityframes.jpg", category: "Art" },
        { id: 25, title: "Messi World cup", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/MessiSports.webp", category: "Music" },
        { id: 26, title: "GNX X Starboy X For All The Dogs", size: "11.7 x 16.5(A3)", price:2999.99, image: "images/siteposters/zkendrick.webp", category: "Music" },
        { id: 27, title: "Ronaldo X Messi X Maradona", size: "11.7 x 16.5(A3)", price: 1999.99, image: "images/siteposters/ZMESSIRON.png", category: "Sports" },
        { id: 28, title: "Cristiano Ronaldo poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/zronaldo.png", category: "Sports" },
        { id: 29, title: "Flower Boy poster", size: "11.7 x 16.5(A3)", price: 999.99, image: "images/siteposters/ztylor.png", category: "Music" },
        { id: 30, title: "Flower Boy X Trilogy:", size: "11.7 x 16.5(A3)", price: 1999.99, image: "images/siteposters/ZTYLORTRILOGY.png", category: "Music" }
    ];