// Poster data with categories
    const posters = [
        { id: 1, title: "Chirping Birds", size: "16x20", price: 1499.99, image: "images/siteposters/birdsnature.png", category: "Art" },
        { id: 2, title: "I Will Blossom", size: "16x20", price: 1499.99, image: "images/siteposters/teee.png", category: "Art" },
        { id: 3, title: "Ducati Superleggera", size: "16x20", price: 2499.99, image: "images/siteposters/doubledugaticars.png", category: "Cars" },
        { id: 4, title: "Circuit de Monaco", size: "16x20", price: 2499.99, image: "images/siteposters/doubleformulasports.png", category: "Sports" },
        { id: 5, title: "Kaizen Japanese", size: "16x20", price: 2499.99, image: "images/siteposters/doubleinspiration.png", category: "Inspirational Quotes" },
        { id: 6, title: "Stylized bonsai tree", size: "16x20", price: 1499.99, image: "images/siteposters/treeNature.webp", category: "Art" },
        { id: 7, title: "The Weeknd Trilogy Music", size: "16x20", price: 1499.99, image: "images/siteposters/trilogymusic.png", category: "Music" },
        { id: 8, title: "The Miseducation of Lauryn Hill", size: "16x20", price: 1499.99, image: "images/siteposters/alauryn.png", category: "Music" },
        { id: 9, title: "SOS Album Cover", size: "16x20", price: 1499.99, image: "images/siteposters/asos.png", category: "Music" },
        { id: 10, title: "Black and White Hands", size: "16x20", price: 1499.99, image: "images/siteposters/twohandss.png", category: "Art" },
        { id: 11, title: "Tyler The Creator Flower Boy", size: "16x20", price: 1499.99, image: "images/siteposters/tylor.png", category: "Music" },
        { id: 12, title: "The Weeknd's album Trilogy", size: "16x20", price: 1499.99, image: "images/siteposters/weekndmusic.png", category: "Music" },
        { id: 13, title: "Skins by XXXTENTACION", size: "16x20", price: 1499.99, image: "images/siteposters/xxmusic.png", category: "Music" },
        { id: 14, title: "Muhammad Ali ", size: "16x20", price: 1499.99, image: "images/siteposters/zalii.png", category: "Inspirational Quotes" },
        { id: 15, title: "McLaren x BMW", size: "16x20", price: 2499.99, image: "images/siteposters/zbmw.png", category: "Cars" },
        { id: 16, title: "Polar Bear x Elephant Poster", size: "16x20", price: 1499.99, image: "images/siteposters/zdoublenature.png", category: "Nature" },
        { id: 17, title: "Ducati Panigale V2 Motorcycle", size: "16x20", price: 2499.99, image: "images/siteposters/ZDUCAtitrimp.png", category: "Cars" },
        { id: 18, title: "Flowers Art", size: "16x20", price: 1499.99, image: "images/siteposters/zflower.png", category: "Art" },
        { id: 19, title: "The Untraveled Road", size: "16x20", price: 1499.99, image: "images/siteposters/zforest.png", category: "Nature" },
        { id: 20, title: "Kenya Country Map and Flag", size: "16x20", price: 2499.99, image: "images/siteposters/zkenyaa.png", category: "Art" },
        { id: 21, title: "Messi x Ronaldo x Maradona", size: "16x20", price: 2499.99, image: "images/siteposters/ZMESSIRON.png", category: "Sports" },
        { id: 22, title: "DERRICK HENRY NFL", size: "16x20", price: 1499.99, image: "images/siteposters/znfl.png", category: "Sports" },
        { id: 23, title: "Cristiano Ronaldo", size: "16x20", price: 1499.99, image: "images/siteposters/zronaldo.png", category: "Sports" },
        { id: 24, title: "Flower Boy by Tyler", size: "16x20", price: 1499.99, image: "images/siteposters/ztylor.png", category: "Music" },
        { id: 25, title: "Flower Boy x Trilogy", size: "16x20", price: 2499.99, image: "images/siteposters/ZTYLORTRILOGY.png", category: "Music" },
        { id: 26, title: "GNX x Starboy x For All The Dogs", size: "16x20", price:3999.99, image: "images/siteposters/zkendrick.webp", category: "Music" },
        { id: 27, title: "The Weekend Collection", size: "16x20", price: 3999.99, image: "images/siteposters/zzweekend.webp", category: "Music" },
        { id: 28, title: "Hurry Up Tomorrow", size: "16x20", price: 1499.99, image: "images/siteposters/zzwek.webp", category: "MMusic" },
        { id: 29, title: "Nostalgia Rodwave", size: "16x20", price: 1499.99, image: "images/siteposters/zzzrodwave.jpeg", category: "Music" },
        { id: 30, title: "The Weeknd's album Trilogy", size: "16x20", price: 1499.99, image: "images/siteposters/zzzweekend.jpeg", category: "Music" },
        { id: 31, title: "Muhammad Ali", size: "16x20", price: 1499.99, image: "images/siteposters/aliiiinspiartion.png", category: "Inspirational Quotes" },
        { id: 32, title: "Muhammad Ali", size: "16x20", price: 1499.99, image: "images/siteposters/aliiinspiration.webp", category: "Inspirational Quotes" },
        { id: 34, title: "BMW M4 GT3", size: "12x12", price: 1499.99, image: "images/siteposters/bmwcarrs.png", category: "Cars" },
        { id: 35, title: "BMW M4 GT3 ", size: "11x14", price: 1499.99, image: "images/siteposters/bmwcars.webp", category: "Cars" },
        { id: 36, title: "Lush floral", size: "24x36", price: 1299.99, image: "images/siteposters/Brown Modern Wall Art Frame Instagram Post.png", category: "Art" },
        { id: 37, title: "Dynamic Basketball Art", size: "16x20", price: 1499.99, image: "images/siteposters/bryantsports.png", category: "Sports" },
        { id: 38, title: "BMW M4 GT3", size: "16x20", price: 1499.99, image: "images/siteposters/carbmw.png", category: "Cars" },
        { id: 40, title: "Flower Boy by Tyler", size: "18x24", price: 1499.99, image: "images/siteposters/creatormusic.png", category: "Music" },
        { id: 41, title: "Chelsea CWC", size: "16x20", price: 1499.99, image: "images/siteposters/cwcsports.jpg", category: "Sports" },
        { id: 42, title: "Sorry 4 What by Tory Lanez", size: "16x20", price: 1499.99, image: "images/siteposters/tory.png", category: "Music" },
        { id: 43, title: "Nature Poster", size: "16x20", price: 1499.99, image: "images/siteposters/tree.png", category: "Art" },
        { id: 45, title: "Michael Jordan x Kobe Bryant", size: "16x20", price: 2499.99, image: "images/siteposters/doublekobe.png", category: "Sports" },
        { id: 46, title: "Interstellar Movie", size: "18x24", price: 1499.99, image: "images/siteposters/doublemovie.png", category: "Movies" },
        { id: 47, title: "Maradona & Messi", size: "20x30", price: 1499.99, image: "images/siteposters/doublemrmessi.png", category: "Sports" },
        { id: 48, title: "Wildlife", size: "24x36", price:1499.99, image: "images/siteposters/doublenature.png", category: "Nature" },
        { id: 49, title: "Lion Mindset", size: "16x20", price: 1499.99, image: "images/siteposters/doublminsett.png", category: "Inspirational Quotes" },
        { id: 50, title: "Ducati Panigale V4 motorcycle", size: "16x20", price: 1499.99, image: "images/siteposters/ducaticars.webp", category: "Cars" },
        { id: 51, title: "Lion Motivation", size: "18x24", price: 1499.99, image: "images/siteposters/easyway.png", category: "Inspirational Quotes" },
        { id: 52, title: "Eminem", size: "18x24", price: 1499.99, image: "images/siteposters/eminem.png", category: "Music" },
        { id: 53, title: "Earthrise-Apollo", size: "18x24", price: 1499.99, image: "images/siteposters/erthrisemovie.png", category: "Movies" },
        { id: 54, title: "Severence Poster", size: "16x20", price: 1499.99, image: "images/siteposters/severencemovie.webp", category: "Movies" },
        { id: 55, title: "Sucess Inspiration", size: "16x20", price: 1499.99, image: "images/siteposters/sucess.png", category: "Inspirational Quotes" },
        { id: 56, title: "Regal Bouquet Elegant Floral", size: "16x20", price: 1499.99, image: "images/siteposters/floweragain.png", category: "Art" },
        { id: 57, title: "Flower Still Life", size: "16x20", price: 1499.99, image: "images/siteposters/floweranature.png", category: "Art" },
        { id: 58, title: "Ronaldo Inspiration", size: "16x20", price: 1499.99, image: "images/siteposters/ronaldo.png", category: "Sports" },
        { id: 59, title: "Flower Still Life", size: "16x20", price: 1499.99, image: "images/siteposters/flowerc.png", category: "Art" },
        { id: 60, title: "Ronaldo Calma", size: "16x20", price: 1499.99, image: "images/siteposters/Ronaldosports.webp", category: "Sports" },
        { id: 61, title: "McLaren Poster", size: "16x20", price: 1499.99, image: "images/siteposters/formulaone.png", category: "Sports" },
        { id: 62, title: "Goat Home Decor", size: "16x20", price: 1499.99, image: "images/siteposters/goatnature.png", category: "Nature" },
        { id: 63, title: "Gone Girl Poster", size: "16x20", price: 1499.99, image: "images/siteposters/goegirlmovie.png", category: "Movies" },
        { id: 64, title: "Gone Girl Poster", size: "16x20", price: 1499.99, image: "images/siteposters/gonegirltmovie.png", category: "Movies" },
        { id: 65, title: "Vintage flowers", size: "16x20", price: 1599.99, image: "images/siteposters/Green Brown nature.png", category: "Art" },
        { id: 66, title: "Henry NFL", size: "16x20", price: 1499.99, image: "images/siteposters/henrynfl.png", category: "Sports" },
        { id: 67, title: "Lion Mindset", size: "16x20", price: 2499.99, image: "images/siteposters/inspirationlion.webp", category: "Inspirational Quotes" },
        { id: 68, title: "Insterstellar Movie", size: "16x20", price: 1499.99, image: "images/siteposters/intermovie.webp", category: "Movies" },
        { id: 69, title: "Insterstellar Movie", size: "16x20", price: 1499.99, image: "images/siteposters/interstelar.png", category: "Movies" },
        { id: 70, title: "Kaizen Motivation", size: "16x20", price: 1499.99, image: "images/siteposters/kaizen.png", category: "Inspirational Quotes" },
        { id: 71, title: "Kaizen Motivation", size: "16x20", price: 1499.99, image: "images/siteposters/kaizenInspiration.png", category: "Inspirational Quotes" },
        { id: 72, title: "The Untraveled Road", size: "16x20", price: 1499.99, image: "images/siteposters/nature.png", category: "Nature" },
        { id: 74, title: "Kenyan flag", size: "16x20", price: 1499.99, image: "images/siteposters/kenyaa.png", category: "Other" },
        { id: 75, title: "kenya", size: "16x20", price: 1499.99, image: "images/siteposters/kenyaaa.png", category: "Other" },
        { id: 76, title: "Kobe Bryant x Michael Jordan", size: "16x20", price: 2499.99, image: "images/siteposters/kobe.png", category: "Sports" },
        { id: 77, title: "Kobe Bryant", size: "16x20", price: 1499.99, image: "images/siteposters/kobee.png", category: "Sports" },
        { id: 79, title: "Let's Go", size: "16x20", price: 1499.99, image: "images/siteposters/letsgo.png", category: "Inspirational Quotes" },
        { id: 80, title: "Messi x Maradona", size: "16x20", price: 1499.99, image: "images/siteposters/maradonasports.webp", category: "Sports" },
        { id: 82, title: "Messi Worldcup", size: "16x20", price: 1499.99, image: "images/siteposters/messi.png", category: "Sports" },
        { id: 84, title: "Messi Worldcup Trophy", size: "16x20", price: 1499.99, image: "images/siteposters/MessiSports.webp", category: "Sports" },
        { id: 88, title: "F1 Monaco Circuit", size: "16x20", price: 1499.99, image: "images/siteposters/monacotwo.png", category: "Cars" },
        { id: 89, title: "Moon Poster", size: "16x20", price: 1499.99, image: "images/siteposters/moon.png", category: "Nature" },
        { id: 90, title: "Parasite Movie", size: "16x20", price: 1499.99, image: "images/siteposters/mparasitemovie.webp", category: "Movies" },
        { id: 92, title: "Darkness Antler", size: "16x20", price: 1499.99, image: "images/siteposters/natureagain.png", category: "Nature" },
        { id: 93, title: "White Tiger", size: "16x20", price: 1499.99, image: "images/siteposters/naturee.png", category: "Nature" },
        { id: 94, title: "Ronaldo At OT", size: "16x20", price: 1499.99, image: "images/siteposters/otronaldo.png", category: "Sports" },
        { id: 95, title: "Lush florals", size: "16x20", price: 2499.99, image: "images/siteposters/oubleflowers.png", category: "Art" },
        { id: 96, title: "Parasite Movie Poster", size: "16x20", price: 1499.99, image: "images/siteposters/parasite.png", category: "Movies" },
        { id: 98, title: "Framed Picture", size: "16x20", price: 1499.99, image: "images/siteposters/persona.png", category: "Other" },
        { id: 100, title: "Ronaldo Motivation", size: "16x20", price: 1499.99, image: "images/siteposters/ronaldsports.webp", category: "Sports" },
        { id: 102, title: "Framed Picture", size: "16x20", price: 1499.99, image: "images/siteposters/personc.png", category: "Other" },
        { id: 103, title: "4 Frames", size: "16x20", price: 4799.99, image: "images/siteposters/qualityframes.jpg", category: "Other" }
    ];